theme: jekyll-theme-architect
title: The WareZone
description: Welcome! This is where I will store all things related to coding for my computer science classes. I primarily use Scratch and Python with my high school students.
